def add(macros):
    # continuous energy equation
    macros["ene"] = [
        "\\pder{k_{#1}}{t}"
        "="
        "-"
        "\\frac{1}{J}"
        "\\pder{}{\\gx}"
        "\\left("
        "   \\jhx"
        "   \\ux k_{#1}"
        "\\right)"
        "-"
        "\\frac{1}{J}"
        "\\pder{}{\\gy}"
        "\\left("
        "   \\jhy"
        "   \\uy k_{#1}"
        "\\right)"
        "-"
        "\\frac{1}{J}"
        "\\pder{}{\\gz}"
        "\\left("
        "   \\jhz"
        "   \\uz k_{#1}"
        "\\right)"
        "-"
        "u_{#1}"
        "\\frac{1}{h_{#1}}"
        "\\pder{p}{\\gcs_{#1}}"
        "+"
        "\\frac{1}{J}"
        "\\pder{}{\\gx}"
        "\\left("
        "   \\jhx"
        "   u_{#1}"
        "   \\tau_{#1 \\vx}"
        "\\right)"
        "+"
        "\\frac{1}{J}"
        "\\pder{}{\\gy}"
        "\\left("
        "   \\jhy"
        "   u_{#1}"
        "   \\tau_{#1 \\vy}"
        "\\right)"
        "+"
        "\\frac{1}{J}"
        "\\pder{}{\\gz}"
        "\\left("
        "   \\jhz"
        "   u_{#1}"
        "   \\tau_{#1 \\vz}"
        "\\right)"
        "-"
        "\\frac{1}{\\hx}"
        "\\pder{u_{#1}}{\\gx}"
        "\\tau_{#1 \\vx}"
        "-"
        "\\frac{1}{\\hy}"
        "\\pder{u_{#1}}{\\gy}"
        "\\tau_{#1 \\vy}"
        "-"
        "\\frac{1}{\\hz}"
        "\\pder{u_{#1}}{\\gz}"
        "\\tau_{#1 \\vz}"
        "+"
        "f_{#1} u_{#1}"
    , 1]
