def add(macros):
    # continuous momentum equation
    macros["mom"] = [
        "\\pder{\\rho u_{#1}}{t}"
        "="
        "-"
        "\\frac{1}{J}"
        "\\pder{}{\\gx}"
        "\\left("
        "   \\jhx"
        "   \\rho \\ux u_{#1}"
        "\\right)"
        "-"
        "\\frac{1}{J}"
        "\\pder{}{\\gy}"
        "\\left("
        "   \\jhy"
        "   \\rho \\uy u_{#1}"
        "\\right)"
        "-"
        "\\frac{1}{J}"
        "\\pder{}{\\gz}"
        "\\left("
        "   \\jhz"
        "   \\rho \\uz u_{#1}"
        "\\right)"
        "-"
        "\\frac{1}{h_{#1}}"
        "\\pder{p}{\\gcs_{#1}}"
        "+"
        "\\frac{1}{J}"
        "\\pder{}{\\gx}"
        "\\left("
        "   \\jhx"
        "   \\tau_{#1 \\vx}"
        "\\right)"
        "+"
        "\\frac{1}{J}"
        "\\pder{}{\\gy}"
        "\\left("
        "   \\jhy"
        "   \\tau_{#1 \\vy}"
        "\\right)"
        "+"
        "\\frac{1}{J}"
        "\\pder{}{\\gz}"
        "\\left("
        "   \\jhz"
        "   \\tau_{#1 \\vz}"
        "\\right)"
        "+"
        "f_{#1}"
    , 1]
