#if !defined(INCLUDE_ARRAY_MACROS_INTERFACE_FLUXX_H)
#define INCLUDE_ARRAY_MACROS_INTERFACE_FLUXX_H

// This file is generated by tools/define_arrays.py

#if NDIMS == 2
// [1 : isize+1], [0 : jsize+1]
#define FLUXX(I, J) (fluxx[(I-1) + (isize+1) * (J  )])
#define FLUXX_NADDS (int [NDIMS][2]){ {0, 1}, {1, 1}, }
#endif

#if NDIMS == 3
// [1 : isize+1], [0 : jsize+1], [0 : ksize+1]
#define FLUXX(I, J, K) (fluxx[(I-1) + (isize+1) * ((J  ) + (jsize+2) * (K  ))])
#define FLUXX_NADDS (int [NDIMS][2]){ {0, 1}, {1, 1}, {1, 1}, }
#endif

#endif // INCLUDE_ARRAY_MACROS_INTERFACE_FLUXX_H
