#if !defined(INCLUDE_ARRAY_MACROS_FLUID_TXX_H)
#define INCLUDE_ARRAY_MACROS_FLUID_TXX_H

// This file is generated by tools/define_arrays.py

// [1 : isize+0], [0 : jsize+1]
#define TXX(I, J) (txx[(I-1) + (isize+0) * (J  )])
#define TXX_NADDS (int [NDIMS][2]){ {0, 0}, {1, 1}, }

#endif // INCLUDE_ARRAY_MACROS_FLUID_TXX_H
