#if !defined(INCLUDE_ARRAY_MACROS_FLUID_TXY_H)
#define INCLUDE_ARRAY_MACROS_FLUID_TXY_H

// This file is generated by tools/define_arrays.py

// [1 : isize+1], [0 : jsize+1], [0 : ksize+1]
#define TXY(I, J, K) (txy[(I-1) + (isize+1) * ((J  ) + (jsize+2) * (K  ))])
#define TXY_NADDS (int [NDIMS][2]){ {0, 1}, {1, 1}, {1, 1}, }

#endif // INCLUDE_ARRAY_MACROS_FLUID_TXY_H
