#if !defined(INCLUDE_ARRAY_MACROS_FLUID_TXZ_H)
#define INCLUDE_ARRAY_MACROS_FLUID_TXZ_H

// This file is generated by tools/define_arrays.py

#if NDIMS == 3
// [1 : isize+1], [0 : jsize+1], [0 : ksize+1]
#define TXZ(I, J, K) (txz[(I-1) + (isize+1) * ((J  ) + (jsize+2) * (K  ))])
#define TXZ_NADDS (int [NDIMS][2]){ {0, 1}, {1, 1}, {1, 1}, }
#endif

#endif // INCLUDE_ARRAY_MACROS_FLUID_TXZ_H
