#if !defined(INCLUDE_ARRAY_MACROS_FLUID_VISUY_H)
#define INCLUDE_ARRAY_MACROS_FLUID_VISUY_H

// This file is generated by tools/define_arrays.py

#if NDIMS == 2
// [0 : isize+1], [0 : jsize+1]
#define VISUY(I, J) (visuy[(I  ) + (isize+2) * (J  )])
#define VISUY_NADDS (int [NDIMS][2]){ {1, 1}, {1, 1}, }
#endif

#if NDIMS == 3
// [0 : isize+1], [0 : jsize+1], [0 : ksize+1]
#define VISUY(I, J, K) (visuy[(I  ) + (isize+2) * ((J  ) + (jsize+2) * (K  ))])
#define VISUY_NADDS (int [NDIMS][2]){ {1, 1}, {1, 1}, {1, 1}, }
#endif

#endif // INCLUDE_ARRAY_MACROS_FLUID_VISUY_H
