# ref: alabaster/support.py

from pygments.style import Style
from pygments.token import (
    Keyword,
    Name,
    Comment,
    String,
    Error,
    Number,
    Operator,
    Generic,
    Whitespace,
    Punctuation,
    Other,
    Literal,
)

# color fliped

class MyAlabaster(Style):
    background_color = "#070707"
    default_style = ""
    styles = {
        Error: "#5BFFFF border:#10D6D6",
        Other: "#FFFFFF",
        Comment: "italic #70A6FD",
        Comment.Preproc: "noitalic",
        Keyword: "bold #FFBB9E",
        Keyword.Constant: "bold #FFBB9E",
        Keyword.Declaration: "bold #FFBB9E",
        Keyword.Namespace: "bold #FFBB9E",
        Keyword.Pseudo: "bold #FFBB9E",
        Keyword.Reserved: "bold #FFBB9E",
        Keyword.Type: "bold #FFBB9E",
        Operator: "#A7D7FF",
        Operator.Word: "bold #FFBB9E",
        Punctuation: "bold #FFFFFF",
        Name: "#FFFFFF",
        Name.Attribute: "#3B5FFF",
        Name.Builtin: "#FFBB9E",
        Name.Builtin.Pseudo: "#CB9A5B",
        Name.Class: "#FFFFFF",
        Name.Constant: "#FFFFFF",
        Name.Decorator: "#888",
        Name.Entity: "#31A3FF",
        Name.Exception: "bold #33FFFF",
        Name.Function: "#FFFFFF",
        Name.Property: "#FFFFFF",
        Name.Label: "#0A86FF",
        Name.Namespace: "#FFFFFF",
        Name.Other: "#FFFFFF",
        Name.Tag: "bold #FFBB9E",
        Name.Variable: "#FFFFFF",
        Name.Variable.Class: "#FFFFFF",
        Name.Variable.Global: "#FFFFFF",
        Name.Variable.Instance: "#FFFFFF",
        Number: "#66FFFF",
        Literal: "#FFFFFF",
        Literal.Date: "#FFFFFF",
        String: "#B165F9",
        String.Backtick: "#B165F9",
        String.Char: "#B165F9",
        String.Doc: "italic #70A6FD",
        String.Double: "#B165F9",
        String.Escape: "#B165F9",
        String.Heredoc: "#B165F9",
        String.Interpol: "#B165F9",
        String.Other: "#B165F9",
        String.Regex: "#B165F9",
        String.Single: "#B165F9",
        String.Symbol: "#B165F9",
        Generic: "#FFFFFF",
        Generic.Deleted: "#5BFFFF",
        Generic.Emph: "italic #FFFFFF",
        Generic.Error: "#10D6D6",
        Generic.Heading: "bold #FFFF7F",
        Generic.Inserted: "#FF5FFF",
        Generic.Output: "#888",
        Generic.Prompt: "#8BACCB",
        Generic.Strong: "bold #FFFFFF",
        Generic.Subheading: "bold #7FFF7F",
        Generic.Traceback: "bold #5BFFFF",
    }

